kubecube-io/KubeCube

pkg/apiserver/cubeapi/resourcemanage/resources/deployment/deployment.go

correct deploy-extend api right

Fix correct deploy extend api get events right

---

pkg/authenticator/token/token.go

delete sensitive infromation in logs
yes
no need case
delete sensitive infromation, only verify token is empty

modify log delete token

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/utils/transport/transport.go

What: add api for create subnamespaceachor and resourcequota
Why: create resourcequota need wait for hnc spread rbac rule to new namespace

Feature: add api for create subnamespaceachor and resourcequota

---

docs/changelog.md

Feature add changelog

---

docs/changelog.md
pkg/apiserver/cubeapi/cluster/handler.go
pkg/utils/transport/transport.go

merge v1.0.0-rc0 into main

---

pkg/warden/localmgr/controllers/hotplug/helm.go
pkg/warden/localmgr/controllers/hotplug/hotplug_controller.go

change way to valid if helm release is installed.
change helm list to helm status, will more correct.

Fix hotplug 

---

cmd/cube/app/options/options.go
hack/install_hotplug.sh
pkg/apiserver/apiserver.go
pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/authorization/helper.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/apiserver/cubeapi/scout/scout.go
pkg/clients/client_manager.go
pkg/ctrlmgr/controllers/cluster/cluster_controller.go
pkg/ctrlmgr/controllers/cluster/helper.go
pkg/ctrlmgr/controllers/cluster/resources.go
pkg/ctrlmgr/manager.go
pkg/multicluster/manager/sync.go
pkg/scout/scout.go
pkg/utils/constants/constants.go
pkg/utils/env/env.go
pkg/utils/transport/transport.go
pkg/warden/reporter/readyz_check.go
pkg/warden/reporter/report.go
pkg/warden/reporter/reporter.go
pkg/warden/server/apiserver.go
pkg/warden/syncmgr/manager.go
pkg/warden/syncmgr/register.go
pkg/warden/utils/client.go

1. filter update event for cluster controller
2. filter event as annotation logic for warden sync controller
3. decouple ClusterInfo api from metric server
3. comment optimize
4. constants optimize
5. mark todos

Optimize: do some optimize for kubecube as bellow:

---

config/samples/hotplug_v1_hotplug.yaml

update hotplug add es config
add hotplug sample

Feature add hotplug demo

---

cmd/cube/main.go
cmd/warden/main.go
docs/changelog.md

add change log for release v1.0.0

add change log for release v1.0.0

---

docs/changelog.md

add change log

---

docs/changelog.md
pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/apiserver/cubeapi/cluster/templates.go
pkg/apiserver/cubeapi/scout/scout.go
pkg/ctrlmgr/controllers/cluster/cluster_controller.go
pkg/ctrlmgr/controllers/cluster/helper.go
pkg/utils/env/env.go

merge 1.0.1 into main
* Bugfix/modify add cluster script (#25)

merge 1.0.1 into main

---

cmd/cube/app/options/flags/auth.go
cmd/cube/main.go
deploy/template/authConfigmap.yaml
deploy/template/featureConfigmap.yaml
pkg/apis/user/v1/user_types.go
pkg/apiserver/apiserver.go
pkg/apiserver/cubeapi/user/auth.go
pkg/authentication/config.go
pkg/authentication/identityprovider/github/config.go
pkg/authentication/identityprovider/github/github.go

add github auth login

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/clients/client_manager.go
pkg/multicluster/manager/multi_clutster_mgr.go

1. add cluster status filter
2. do panic when connect to pivot cluster failed

add cluster status filter

---

cmd/cube/app/options/flags/auth.go
pkg/authentication/config.go
pkg/authentication/identityprovider/generic/generic.go

generic auth method add https scheme
no

generic auth url add https scheme

---

pkg/apiserver/cubeapi/resourcemanage/handle/extend.go
pkg/apiserver/cubeapi/resourcemanage/resources/service/service.go

Feature add service external ips

---

pkg/quota/k8s/operator.go

fix logic of resource quota webhook for conformance need

fix resource quota conformance

---

docs/changelog.md

add v1.0.2 changelog

---

pkg/ctrlmgr/controllers/tenant/tenant_controller.go

add tenant ns annotations
hnc will get it and create labels 

[bugfix] add tenant ns annotation

---

docs/changelog.md

Feature add changlog

---

docs/changelog.md
pkg/ctrlmgr/controllers/tenant/tenant_controller.go

Merge Release v1.0.3 into main

Merge Release v1.0.3 into main

---

pkg/apiserver/cubeapi/resourcemanage/handle/proxy.go
pkg/scout/scout.go
pkg/warden/localmgr/controllers/hotplug/hotplug_controller.go

1、fix proxy http and https
2、fix hotplug result status error

Bugfix fix proxy http

---

README.md

add  badge of Certified Kubernetes
yes,fix the wrong link of license in readme

add Certified Kubernetes badge

---

cmd/cube/app/options/flags/auth.go
pkg/apiserver/cubeapi/key/handle.go
pkg/apiserver/cubeapi/key/key_test.go
pkg/apiserver/cubeapi/user/auth.go
pkg/apiserver/cubeapi/user/user.go
pkg/apiserver/middlewares/auth/auth.go
pkg/authentication/authenticators/jwt/jwt.go
pkg/authentication/authenticators/jwt/jwt_test.go
pkg/authentication/authenticators/manager.go
pkg/authentication/authenticators/token/token.go
pkg/warden/server/apis.go

fix jwt function to interface

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/key/handle.go
pkg/apiserver/cubeapi/key/key_test.go
pkg/apiserver/cubeapi/resourcemanage/handle/extend.go
pkg/apiserver/middlewares/audit/audit.go
pkg/apiserver/middlewares/auth/auth.go
pkg/authentication/authenticators/token/token.go
pkg/authentication/authenticators/token/token_test.go

fix get userinfo or token from http request

fix get userinfo or token from request

---

pkg/apiserver/cubeapi/user/auth.go

hide user password when login

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/healthz/healthy.go
pkg/apiserver/cubeapi/key/handle.go
pkg/apiserver/cubeapi/user/auth.go
pkg/apiserver/cubeapi/user/user.go
pkg/apiserver/middlewares/audit/audit.go
pkg/apiserver/middlewares/audit/audit_test.go
pkg/apiserver/middlewares/auth/auth.go
pkg/utils/audit/constants.go
pkg/utils/constants/constants.go

1. fix middleware whitelist filter with regexp
2. optimize audit code

fix middleware whitelist filter with regexp

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/authorization/helper.go
pkg/apiserver/cubeapi/cluster/handler.go

1. fix: can not add the customize ClusterRole
2. add namespace list content

fix: can not add the customize ClusterRole

---

go.mod
go.sum
pkg/warden/server/apiserver.go
pkg/warden/server/authproxy/authproxy.go
pkg/warden/server/authproxy/proxy/dial.go
pkg/warden/server/authproxy/proxy/dial_test.go
pkg/warden/server/authproxy/proxy/doc.go
pkg/warden/server/authproxy/proxy/transport.go
pkg/warden/server/authproxy/proxy/transport_test.go
pkg/warden/server/authproxy/proxy/upgradeaware.go
pkg/warden/server/authproxy/proxy/upgradeaware_test.go
pkg/warden/server/authproxy/upgrade.go
vendor/github.com/mxk/go-flowrate/LICENSE
vendor/github.com/mxk/go-flowrate/flowrate/flowrate.go
vendor/github.com/mxk/go-flowrate/flowrate/io.go
vendor/github.com/mxk/go-flowrate/flowrate/util.go
vendor/github.com/stretchr/testify/require/doc.go
vendor/github.com/stretchr/testify/require/forward_requirements.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require.go.tmpl
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
vendor/github.com/stretchr/testify/require/requirements.go
vendor/golang.org/x/net/websocket/client.go
vendor/golang.org/x/net/websocket/dial.go
vendor/golang.org/x/net/websocket/hybi.go
vendor/golang.org/x/net/websocket/server.go
vendor/golang.org/x/net/websocket/websocket.go
vendor/modules.txt

auth-proxy support proxy for kubectl exec operation

enhance: auth-proxy support for exec op

---

pkg/apiserver/cubeapi/user/auth.go
pkg/apiserver/middlewares/audit/audit.go
pkg/apiserver/middlewares/auth/auth.go

fix white list filter method in middlewares

fix white list filter method in middlewares

---

docs/changelog.md

add v1.1.0 changelog

---

pkg/multicluster/manager/multi_clutster_mgr.go

deepcopy for internal cluster

---

pkg/clients/kubernetes/kubernetes.go
pkg/ctrlmgr/controllers/cluster/cluster_controller.go
pkg/ctrlmgr/controllers/cluster/helper.go
pkg/ctrlmgr/controllers/cluster/resources.go
pkg/multicluster/manager/multi_clutster_mgr.go
pkg/multicluster/manager/scout.go
pkg/utils/update.go

fix and optimize cluster reconcile

fix and optimize cluster reconcile

---

pkg/apiserver/cubeapi/yamldeploy/yamldeploy.go

yaml deploy change to restclient and use username to auth

[update]yaml deploy change to restclient

---

pkg/apiserver/middlewares/auth/auth.go
pkg/multicluster/client/clinet.go
pkg/multicluster/client/fake/client.go

kubecube client interface add restful, restmappper, discovery clients

kubecube client add restful, restmappper, discovery

---

pkg/apiserver/middlewares/audit/audit.go

fix audit middleware to a goroutine

fix audit middleware to a goroutine

---

pkg/ctrlmgr/controllers/quota/cuberesourcequota_controller.go
pkg/quota/k8s/operator.go
pkg/quota/k8s/populate.go

remove not exist subResourceQuota

remove not exist subResourceQuota

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/ctrlmgr/controllers/cluster/cluster_controller.go

cluster info add cpu and mem used quota

cluster info add cpu and mem used quota

---

pkg/apiserver/middlewares/audit/audit.go
pkg/authentication/authenticators/jwt/jwt.go
pkg/utils/constants/constants.go

fix bug: request to login makes error logs in audit middleware
no

fix: login api make error log

---

pkg/conversion/conversion.go
pkg/conversion/conversion_test.go

Fix version conversion

---

docs/changelog.md

add change log for v1.2.0

---

docs/changelog.md

update change log

---

pkg/apiserver/cubeapi/resourcemanage/handle/extend.go
pkg/authentication/identityprovider/github/config.go
pkg/ctrlmgr/controllers/cluster/helper.go
pkg/ctrlmgr/controllers/cluster/resources.go
pkg/ctrlmgr/manager.go
pkg/multicluster/fake.go
pkg/multicluster/interface.go
pkg/multicluster/manager.go
pkg/utils/constants/constants.go
pkg/utils/env/env.go
pkg/utils/international/manager.go
pkg/warden/localmgr/controllers/hotplug/hotplug_controller.go
pkg/warden/localmgr/controllers/hotplug/util.go
pkg/warden/localmgr/manager.go
pkg/warden/localmgr/setup.go
pkg/warden/localmgr/webhooks/hotplug/hotplug.go
pkg/warden/warden.go

support for customize namespace

support for customize namespace

---

pkg/warden/reporter/report.go

add logs for warden reporter

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/ctrlmgr/controllers/project/project_controller.go
pkg/ctrlmgr/controllers/project/project_controller_test.go
pkg/ctrlmgr/controllers/tenant/tenant_controller.go
pkg/ctrlmgr/webhooks/project/project_validator.go
pkg/ctrlmgr/webhooks/project/project_validator_test.go
pkg/ctrlmgr/webhooks/tenant/tenant_validator.go
pkg/ctrlmgr/webhooks/tenant/tenant_validator_test.go
pkg/multicluster/manager.go
pkg/utils/constants/constants.go
test/e2e/tenant/tenant.go

support get clusters by related project

support get clusters by related project

---

pkg/utils/constants/constants.go
pkg/utils/env/env.go

modify svc const

---

cmd/cube/app/options/flags/apiserver.go
pkg/apiserver/cubeapi/resourcemanage/handle/extend.go
pkg/apiserver/cubeapi/resourcemanage/handle/proxy.go
pkg/authentication/identityprovider/github/config.go
pkg/conversion/client.go
pkg/conversion/conversion.go
pkg/conversion/interface.go
pkg/ctrlmgr/controllers/cluster/helper.go
pkg/ctrlmgr/controllers/cluster/resources.go
pkg/ctrlmgr/manager.go
pkg/multicluster/client/client.go
pkg/multicluster/fake.go
pkg/multicluster/interface.go
pkg/multicluster/manager.go
pkg/utils/constants/constants.go
pkg/utils/env/env.go
pkg/utils/international/manager.go
pkg/warden/localmgr/controllers/hotplug/hotplug_controller.go
pkg/warden/localmgr/controllers/hotplug/util.go
pkg/warden/localmgr/manager.go
pkg/warden/localmgr/setup.go
pkg/warden/localmgr/webhooks/hotplug/hotplug.go
pkg/warden/reporter/report.go
pkg/warden/warden.go

Optimize version convert to support wrap client.Client

Optimize version convert

---

pkg/quota/cube/operator.go
pkg/quota/cube/populate.go
pkg/quota/k8s/populate.go

fix resource quota populate

---

pkg/ctrlmgr/controllers/cluster/helper.go
pkg/utils/env/env.go

support retain resources in member cluster

support retain resources in member cluster

---

pkg/ctrlmgr/controllers/crds/crds_controller.go
pkg/ctrlmgr/controllers/setup.go

auto add crd rule to rbac rules

Support rbac for crds

---

pkg/utils/filter/filter.go

Fix filter body

---

pkg/apiserver/cubeapi/user/user.go

get user form context

---

deploy/manifests/rbac/buildin/platform-admin-ag.yaml
deploy/manifests/rbac/buildin/platform-admin.yaml
deploy/manifests/rbac/buildin/project-admin-ag.yaml
deploy/manifests/rbac/buildin/project-admin-cluster-ag.yaml
deploy/manifests/rbac/buildin/project-admin-cluster.yaml
deploy/manifests/rbac/buildin/project-admin.yaml
deploy/manifests/rbac/buildin/reviewer-ag.yaml
deploy/manifests/rbac/buildin/reviewer.yaml
deploy/manifests/rbac/buildin/tenant-admin-ag.yaml
deploy/manifests/rbac/buildin/tenant-admin-cluster-ag.yaml
deploy/manifests/rbac/buildin/tenant-admin-cluster.yaml
deploy/manifests/rbac/buildin/tenant-admin.yaml
pkg/ctrlmgr/controllers/setup.go
pkg/warden/localmgr/controllers/crds/crds_controller.go
pkg/warden/localmgr/setup.go

move crd controller to warden

---

pkg/apiserver/cubeapi/authorization/handler.go

Get user form context for auth

Get user form context for auth

---

pkg/apiserver/middlewares/audit/audit.go

Fix array out of bounds in audit middleware

Fix audit outbound

---

deploy/manifests/rbac/buildin/platform-admin-ag.yaml
deploy/manifests/rbac/buildin/project-admin-ag.yaml
deploy/manifests/rbac/buildin/reviewer-ag.yaml
deploy/manifests/rbac/buildin/tenant-admin-ag.yaml
pkg/apiserver/cubeapi/authorization/handler.go
pkg/authorizer/rbac/extractor.go
pkg/quota/cube/populate.go
pkg/quota/k8s/populate.go
pkg/warden/syncmgr/register.go

Apis support query multi resources access

Apis support multi auth

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/multicluster/scout/scout.go

Fix get assigned resource

---

pkg/apiserver/cubeapi/resourcemanage/handle/extend.go
pkg/ctrlmgr/webhooks/cluster/cluster_validator.go
pkg/ctrlmgr/webhooks/hotplug/hotplug_validate.go
pkg/utils/domain/domainsuffix.go
pkg/utils/strslice/strings.go
pkg/utils/strslice/strings_test.go
pkg/warden/localmgr/webhooks/hotplug/hotplug.go
pkg/warden/localmgr/webhooks/project/project_validator.go
pkg/warden/localmgr/webhooks/tenant/tenant_validator.go

add repeat ingress domain suffix identification
no
pkg/utils/strslice/strings_test.go#TestRepeatString
run test case

add repeat ingress domain suffix identification

---

docs/changelog.md

Add v1.2.1 changelog

---

pkg/ctrlmgr/controllers/cluster/helper.go

fix cluster nil pointor

---

docs/changelog.md

add v1.2.2 change log

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/user/user.go
pkg/ctrlmgr/controllers/cluster/resources.go
pkg/utils/env/env.go
pkg/utils/response/response.go

get kubeconfig return file

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/authorization/helper.go
pkg/apiserver/cubeapi/cluster/handler.go
pkg/authorizer/rbac/interface.go
pkg/utils/constants/constants.go

add auth access about readable and writable

---

docs/changelog.md

add v1.2.3 changelog

---

pkg/apiserver/apiserver.go
pkg/apiserver/cubeapi/resourcemanage/handle/param.go
pkg/apiserver/cubeapi/resourcemanage/resources/enum/enum.go
pkg/apiserver/cubeapi/resourcemanage/resources/node/constant.go
pkg/apiserver/cubeapi/resourcemanage/resources/node/node.go
pkg/apiserver/cubeapi/resourcemanage/resources/register/register.go
pkg/utils/filter/filter.go

add node info extend func, so we can get node status in extend info and can filter with this

Feature support node selector

---

config/crd/bases/cluster.kubecube.io_clusters.yaml
pkg/apis/cluster/v1/cluster_types.go

add field in cluster crd, which can identify this cluster can be writing

Feature sign cluster iswritleable

---

pkg/apis/user/v1/user_types.go

user spec add wechat

---

cmd/warden/app/options/flags.go
pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/warden/config.go
pkg/warden/reporter/report.go
pkg/warden/reporter/reporter.go
pkg/warden/warden.go

support set cluster is writable

---

docs/changelog.md

Add v1.2.5 changelog

---

pkg/ctrlmgr/manager.go
pkg/multicluster/sync.go

Optimize mutli cluster sync logic

optimize multi cluster sync logic

---

config/crd/bases/cluster.kubecube.io_clusters.yaml
config/crd/bases/user.kubecube.io_users.yaml
pkg/apis/cluster/v1/cluster_types.go

update cluster crd

---

pkg/ctrlmgr/controllers/quota/cuberesourcequota_controller.go
pkg/ctrlmgr/webhooks/quota/cube_resource_quota_v.go
pkg/quota/cube/operator.go
pkg/quota/k8s/operator.go
pkg/quota/utils.go
pkg/warden/localmgr/controllers/quota/quota_controller.go
pkg/warden/localmgr/setup.go
pkg/warden/localmgr/webhooks/quota/resource_quota_v.go

move resourcequota process form webhook to controller

move resourcequota process form webhook to controller

---

docs/changelog.md

add v1.3.0 changelog

---

pkg/multicluster/manager.go

fix multi cluster add error

---

docs/changelog.md

add v1.3.1 changelog

---

pkg/apiserver/cubeapi/cluster/helper.go
pkg/ctrlmgr/webhooks/cluster/cluster_validator.go
pkg/multicluster/manager.go
pkg/utils/constants/constants.go

Support cluster cn name

---

pkg/apiserver/cubeapi/authorization/handler.go

fix auth access api

---

pkg/conversion/client.go
pkg/conversion/conversion.go
pkg/conversion/conversion_test.go

version convert fix list bug

---

docs/changelog.md

add v1.4.0 changelog

---

pkg/apiserver/cubeapi/cluster/handler.go

Fix mem back to v1.3

---

pkg/apiserver/cubeapi/cluster/handler.go

fix capacity memory back

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/warden/localmgr/setup.go

get cluster resource support filter

get cluster resource support filter

---

docs/changelog.md

add v1.4.2 changelog

---

pkg/apiserver/cubeapi/resourcemanage/handle/proxy.go
pkg/apiserver/cubeapi/resourcemanage/resources/pod/pod.go
pkg/utils/filter/filter.go
pkg/utils/selector/selector.go

In some cases, we want to filter the pods based on the owner UID, but in reality, the Deployment controller is ReplicaSet, so it is necessary to query another layer of ReplicaSet to filter the pods

support list pod by owner uid like deployment uid

---

pkg/apiserver/cubeapi/cluster/handler.go

fix namespace display abnormal

fix namespace display abnormal

---

pkg/apiserver/cubeapi/resourcemanage/resources/service/externalaccess.go

optimized port check implementation, when externalPort is nil, skip it

feat:<ingress> optimized port check implementation

---

docs/changelog.md
pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/warden/localmgr/setup.go

Release v1.4

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/authorization/helper.go
pkg/apiserver/cubeapi/cluster/handler.go

When querying the associated project and Namespace of a tenant, you can use multiple tenants as filtering conditions

feat:<tenant> get namespaces and project by multi tenant

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/resourcemanage/handle/extend.go
pkg/apiserver/cubeapi/user/auth.go
pkg/apiserver/cubeapi/user/user.go
pkg/apiserver/cubeapi/yamldeploy/yamldeploy.go
pkg/apiserver/middlewares/audit/audit.go
pkg/apiserver/middlewares/auth/auth.go
pkg/authentication/identityprovider/generic/generic.go
pkg/authentication/identityprovider/github/github.go
pkg/authentication/identityprovider/identity_provider.go
pkg/authentication/identityprovider/ldap/ldap.go
pkg/utils/constants/constants.go

fix audit eventTime and userIdentity field
no

fix audit eventTime and userIdentity field

---

pkg/apiserver/cubeapi/healthz/healthy.go

[typos] Fix the swag annotations for HealthyCheck

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go

optimize cluster info api and add query flag for simplify info

optimize cluster info api and add query flag for simplify info

---

pkg/ctrlmgr/webhooks/cluster/cluster_validator.go

widen the number of characters in the cluster name to 100

widen the number of characters in the cluster name to 100

---

docs/changelog.md

add 1.6.1 changelog

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/utils/strproc/strproc.go

feature: add cluster livedata api for slow loading.

feature: add cluster livedata api

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/utils/constants/constants.go

Fix get ns apis

---

pkg/apiserver/cubeapi/resourcemanage/handle/proxy.go
pkg/utils/constants/constants.go
pkg/utils/request/request.go
pkg/warden/server/authproxy/authproxy.go

add fieldManager for proxy api

Feat fieldmanager

---

docs/changelog.md
pkg/apiserver/cubeapi/resourcemanage/handle/proxy.go

fix proxy func label selector bug

fix proxy func label selector

---

pkg/apiserver/cubeapi/cluster/helper.go

Fix cluster info abnormal return

fix cluster info abnormal return

---

config/crd/bases/user.kubecube.io_users.yaml
pkg/apis/user/v1/helpers.go
pkg/apis/user/v1/user_types.go
pkg/apiserver/cubeapi/resourcemanage/handle/proxy.go
pkg/belongs/belongs.go
pkg/belongs/determine.go
pkg/ctrlmgr/controllers/binding/clusterrolebinding_controller.go
pkg/ctrlmgr/controllers/binding/common.go
pkg/ctrlmgr/controllers/binding/rolebinding_controller.go
pkg/ctrlmgr/controllers/setup.go
pkg/utils/constants/constants.go
pkg/utils/constants/k8s_kinds.go
pkg/utils/constants/k8s_resources.go
pkg/utils/path/parse.go
pkg/warden/server/authproxy/authproxy.go

Add user raletionship

---

docs/changelog.md

add v1.7.2 changelog

---

pkg/warden/localmgr/controllers/quota/quota_controller.go

add filter for resourcequota controller

add filter for resourcequota controller

---

docs/changelog.md

add v1.5.3 changelog

---

docs/changelog.md
pkg/apiserver/cubeapi/resourcemanage/resources/node/node.go

fix node result (#227)

---

pkg/quota/k8s/operator.go
pkg/quota/k8s/populate.go
pkg/utils/env/env.go

fix resourcequota set

---

pkg/apiserver/cubeapi/cluster/helper.go

fix ns cluster judge

---

pkg/warden/localmgr/controllers/quota/quota_controller.go

fix resourcequota controller filter

---

pkg/utils/env/env.go
pkg/warden/localmgr/controllers/project/project_controller.go
pkg/warden/localmgr/controllers/project/project_controller_test.go
pkg/warden/localmgr/controllers/tenant/tenant_controller.go

Support customize hnc ns labels

support customize ns labels

---

pkg/utils/env/env.go
pkg/warden/localmgr/controllers/project/project_controller.go
pkg/warden/localmgr/controllers/tenant/tenant_controller.go

Support delete hnc ns labels

---

docs/changelog.md

add v1.7.5 changelog

---

cmd/cube/app/options/flags/auth.go
pkg/authentication/config.go
pkg/authentication/identityprovider/generic/generic.go
pkg/utils/ctls/transport.go
pkg/warden/reporter/reporter.go

fix auth new transport

---

docs/changelog.md

Add v1.7.7 changelog

---

cmd/cube/app/options/flags/ctrlmgr.go
cmd/warden/app/options/flags.go
pkg/ctrlmgr/config.go
pkg/ctrlmgr/controllers/setup.go
pkg/ctrlmgr/manager.go
pkg/utils/ctrlopts/controller_options.go
pkg/warden/config.go
pkg/warden/localmgr/manager.go
pkg/warden/localmgr/setup.go
pkg/warden/warden.go

feat: allowed to enable controllers by options

feat: allowed to enable controllers by options

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/authorization/helper.go
pkg/authorizer/mapping/mapping.go
pkg/authorizer/mapping/mapping_test.go
pkg/utils/constants/constants.go

New auth feat

---

pkg/warden/localmgr/controllers/service/service_controller.go

modify svc controller log level to debug

modify svc controller log level to debug

---

cmd/cube/app/options/flags/auth.go
cmd/cube/app/options/flags/ctrlmgr.go
docs/changelog.md
pkg/authentication/config.go
pkg/authentication/identityprovider/generic/generic.go
pkg/ctrlmgr/controllers/binding/clusterrolebinding_controller.go
pkg/ctrlmgr/controllers/binding/rolebinding_controller.go
pkg/ctrlmgr/controllers/cluster/cluster_controller.go
pkg/ctrlmgr/controllers/quota/cuberesourcequota_controller.go
pkg/ctrlmgr/controllers/setup.go
pkg/ctrlmgr/controllers/user/user_controller.go
pkg/ctrlmgr/manager.go
pkg/ctrlmgr/options/options.go
pkg/multicluster/manager.go
pkg/multicluster/scout/scout.go
pkg/multicluster/sync.go
pkg/utils/ctls/transport.go
pkg/utils/ctrlopts/controller_options.go
pkg/warden/reporter/reporter.go

fix heartbeat report and merge 1.7.7 back to main

fix heartbeat report and merge 1.7.7 back to main

---

docs/changelog.md

add v1.8.0 changelog

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/authorization/helper.go
pkg/apiserver/cubeapi/cluster/handler.go
pkg/authorizer/mapping/mapping.go
pkg/utils/constants/constants.go

Fix auth get permission and modify project and tenant belongs judgement

Fix auth get permission

---

docs/changelog.md

add v1.8.1 changelog

---

pkg/apiserver/cubeapi/authorization/handler.go

modify permission cm data

---

pkg/belongs/belongs.go

modify node judgement

---

docs/changelog.md

Add changelog v1.8.1

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/utils/constants/constants.go

fix node gpu key

---

pkg/ctrlmgr/controllers/binding/clusterrolebinding_controller.go
pkg/ctrlmgr/controllers/binding/common.go
pkg/ctrlmgr/controllers/binding/rolebinding_controller.go

fix binding ctrl

---

pkg/apiserver/cubeapi/authorization/handler.go

fix get projects

---

pkg/apiserver/cubeapi/authorization/handler.go

fix create binding

---

pkg/apiserver/cubeapi/cluster/handler.go

support namespace fuzzy match

---

pkg/multicluster/sync.go

fix multi cluster sdk delete problem

---

docs/changelog.md

add v1.8.2 changelog

---

cmd/cube/app/options/flags/auth.go
pkg/authentication/config.go
pkg/authentication/identityprovider/generic/generic.go
pkg/utils/ctls/transport.go
pkg/warden/reporter/reporter.go

* fix auth new transport
* fix auth new transport
* fix auth new transport
* fix auth new transport
* fix auth new transport
* fix auth new transport

fix auth new transport (#247)

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/cluster/handler.go

add api sort

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/key/handle.go
pkg/apiserver/cubeapi/resourcemanage/handle/extend.go
pkg/apiserver/cubeapi/resourcemanage/handle/proxy.go
pkg/apiserver/cubeapi/user/user.go
pkg/apiserver/cubeapi/yamldeploy/yamldeploy.go
pkg/apiserver/middlewares/precheck/precheck.go
pkg/utils/errcode/common.go
pkg/utils/errcode/def.go

optimize api errors

---

pkg/apiserver/middlewares/audit/audit.go
pkg/utils/env/env.go

audit middleware support to config request headers who is recorded
no

audit middleware support to config request headers who is recorded

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/cluster/handler.go

Reverse time sort

---

pkg/apiserver/cubeapi/cluster/handler.go

add fuzzy match for get subnamespace

---

pkg/apiserver/cubeapi/yamldeploy/yamldeploy.go

support multi yaml deploy

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/utils/access/access.go
pkg/utils/constants/k8s_resources.go

support daemonsets level

---

docs/changelog.md

add v1.8.3 changelog

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go

Add paginate for cluster infos

Add paginate for cluster infos

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/utils/constants/constants.go

fix gpu const

---

docs/changelog.md

add v1.7.8 changelog

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go

Fix filter cluster by project

---

pkg/multicluster/sync.go

ignore cluster init error and keep retry background

ignore cluster init error and keep retry background

---

docs/changelog.md

add changelog v1.8.4

---

cmd/cube/app/cube.go
cmd/cube/app/options/flags/cube.go
cmd/warden/app/options/flags.go
cmd/warden/app/warden.go
pkg/cube/config.go
pkg/warden/config.go

Feat expose klog set

---

pkg/apiserver/apiserver.go
pkg/apiserver/cubeapi/key/handle.go
pkg/apiserver/cubeapi/resourcemanage/handle/extend.go
pkg/apiserver/cubeapi/resourcemanage/handle/extend_test.go
pkg/apiserver/cubeapi/resourcemanage/handle/param.go
pkg/apiserver/cubeapi/resourcemanage/resources/configmap/configmap.go
pkg/apiserver/cubeapi/resourcemanage/resources/cronjob/cronjob.go
pkg/apiserver/cubeapi/resourcemanage/resources/deployment/deployment.go
pkg/apiserver/cubeapi/resourcemanage/resources/deployment/deployment_test.go
pkg/apiserver/cubeapi/resourcemanage/resources/enum/enum.go
pkg/apiserver/cubeapi/resourcemanage/resources/job/job.go
pkg/apiserver/cubeapi/resourcemanage/resources/job/job_test.go
pkg/apiserver/cubeapi/resourcemanage/resources/node/constant.go
pkg/apiserver/cubeapi/resourcemanage/resources/node/node.go
pkg/apiserver/cubeapi/resourcemanage/resources/pod/pod.go
pkg/apiserver/cubeapi/resourcemanage/resources/pvc/pvc.go
pkg/apiserver/cubeapi/resourcemanage/resources/pvc/pvcworkloads.go
pkg/apiserver/cubeapi/resourcemanage/resources/pvc/pvcworkloads_test.go
pkg/apiserver/cubeapi/resourcemanage/resources/register/register.go
pkg/apiserver/cubeapi/resourcemanage/resources/replicaset/replicaset.go
pkg/apiserver/cubeapi/resourcemanage/resources/service/externalaccess.go
pkg/apiserver/cubeapi/resourcemanage/resources/service/externalaccess_test.go
pkg/apiserver/cubeapi/resourcemanage/resources/service/externaladdress.go
pkg/apiserver/cubeapi/resourcemanage/resources/service/service.go
pkg/apiserver/cubeapi/user/user.go
pkg/apiserver/cubeapi/yamldeploy/yamldeploy.go
pkg/apiserver/middlewares/audit/audit.go
pkg/apiserver/middlewares/audit/audit_test.go
pkg/utils/audit/constants.go
pkg/utils/errcode/key.go

add configmap history

---

pkg/apiserver/apiserver.go
pkg/clog/zap.go

support to change log level by api request when running
no

support to change log level when running

---

pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/apiserver/cubeapi/key/key_test.go
pkg/apiserver/cubeapi/resourcemanage/handle/proxy.go
pkg/apiserver/cubeapi/resourcemanage/resources/service/externalaccess.go
pkg/apiserver/cubeapi/user/user.go
pkg/apiserver/middlewares/audit/audit.go
pkg/apiserver/middlewares/auth/auth.go
pkg/ctrlmgr/controllers/cluster/resources.go
pkg/ctrlmgr/webhooks/project/help.go
pkg/utils/constants/constants.go
pkg/utils/filter/help.go
pkg/warden/localmgr/controllers/binding/clusterrolebinding_controller.go
pkg/warden/localmgr/controllers/binding/common.go
pkg/warden/localmgr/controllers/binding/rolebinding_controller.go
pkg/warden/localmgr/controllers/crds/crds_controller.go
pkg/warden/localmgr/controllers/service/service_controller.go
pkg/warden/localmgr/controllers/tenant/tenant_controller.go
pkg/warden/server/authproxy/proxy/upgradeaware.go

optimize code lint

---

docs/changelog.md

Add v1.8.5 changelog

---

cmd/cube/app/options/flags/apiserver.go
docs/changelog.md
pkg/apiserver/apiserver.go
pkg/apiserver/config.go

Add switch for swag

---

pkg/apiserver/cubeapi/resourcemanage/handle/podlog.go
pkg/apiserver/cubeapi/resourcemanage/handle/proxy.go
pkg/apiserver/cubeapi/user/user_test.go
pkg/apiserver/middlewares/audit/audit.go
pkg/authentication/authenticators/token/token_test.go
pkg/authentication/identityprovider/generic/generic.go
pkg/authentication/identityprovider/github/github.go
pkg/utils/ctls/transport.go
pkg/utils/filter/filter.go
pkg/utils/kubeconfig/kubeconfig.go
pkg/warden/localmgr/controllers/hotplug/helm_test.go
pkg/warden/reporter/reporter.go
pkg/warden/server/authproxy/proxy/transport.go
pkg/warden/server/authproxy/proxy/transport_test.go
test/e2e/e2e.go
test/e2e/framework/httphelper.go
test/e2e/k8sproxy/k8sproxy.go
test/e2e/openapi/key.go
test/e2e/yamldeploy/yamldeploy.go

chore: remove refs to deprecated io/ioutil

---

pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go

fix list cube resource quota

---

docs/changelog.md
pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/authorization/helper.go
pkg/apiserver/cubeapi/cluster/handler.go
pkg/apiserver/cubeapi/cluster/helper.go
pkg/multicluster/manager.go
pkg/utils/meta/meta.go

add list cube resource quota

---

docs/changelog.md
pkg/utils/constants/constants.go
pkg/warden/syncmgr/gc.go
pkg/warden/syncmgr/manager.go
pkg/warden/syncmgr/resources.go
pkg/warden/utils/client.go
pkg/warden/warden.go

Add gc coroutine in warden to fix the remaining resources on the compute cluster.

fix remaining resources

---

config/crd/bases/user.kubecube.io_users.yaml
pkg/apis/user/v1/helpers.go
pkg/apis/user/v1/user_types.go
pkg/apiserver/cubeapi/authorization/handler.go
pkg/apiserver/cubeapi/authorization/helper.go
pkg/ctrlmgr/controllers/user/user_controller.go
pkg/utils/transition/transition.go
pkg/warden/localmgr/controllers/user/helper.go
pkg/warden/localmgr/controllers/user/ns_handler.go
pkg/warden/localmgr/controllers/user/user_controller.go

When binding a user as a project role, also bind the tenant information to which the project belongs.

update user belong to project info

---

pkg/apiserver/cubeapi/cluster/helper.go
pkg/utils/env/env.go
pkg/warden/localmgr/controllers/project/project_controller.go
pkg/warden/localmgr/controllers/tenant/tenant_controller.go

default cluster name if empty
add a choice to create tenant project ns or not

add a choice to create tenant project ns or not

---

cmd/cube/app/options/flags/ctrlmgr.go
cmd/warden/app/options/flags.go
docs/changelog.md
pkg/ctrlmgr/controllers/binding/clusterrolebinding_controller.go
pkg/ctrlmgr/controllers/binding/rolebinding_controller.go
pkg/ctrlmgr/controllers/cluster/cluster_controller.go
pkg/ctrlmgr/controllers/quota/cuberesourcequota_controller.go
pkg/ctrlmgr/controllers/setup.go
pkg/ctrlmgr/controllers/user/user_controller.go
pkg/ctrlmgr/manager.go
pkg/ctrlmgr/options/options.go
pkg/multicluster/manager.go
pkg/multicluster/scout/scout.go
pkg/multicluster/sync.go
pkg/utils/ctrlopts/controller_options.go
pkg/warden/config.go
pkg/warden/localmgr/manager.go
pkg/warden/localmgr/setup.go
pkg/warden/warden.go

Fix scout heartbeat

---

config/crd/bases/user.kubecube.io_users.yaml
pkg/apis/user/v1/user_types.go

update user api
